variables:
  DOCKER_DRIVER: overlay
  DOCKER_HOST: unix:///var/run/docker.sock

stages:
  - build
  - deploy

docker-build:
  image: maven:3.9.6-eclipse-temurin-21
  stage: build
  before_script:
    - apt-get update && apt-get install -y make
  script:
    - make docker
  artifacts:
    paths:
      - docker-build/

deploy:
  image: docker:latest
  stage: deploy
  services:
    - name: docker:dind
      command: ["--host=unix:///var/run/docker.sock"]
  script:
    - cd docker-build/docker && docker-compose up --build
  only:
    - microservices