spring.application.name=FQWorkstation-protocol
template.file.path=classpath:template.docx
server.port=13134
number.of.threads=2
server.fqw.url=http://localhost:13131

spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=64MB
spring.servlet.multipart.max-file-size=64MB
spring.servlet.multipart.max-request-size=64MB
server.tomcat.connection-timeout=60000