version: '3'

services:
  db:
    build:
      context:  ../db
    environment:
      - POSTGRES_DB=info-system-department,data-support
      - POSTGRES_USER=temp
      - POSTGRES_PASSWORD=temp
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ../db/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
  fqw:
    build: ../fqw
    ports:
      - "13130:13130"
    depends_on:
      - db
    volumes:
      - ../fqw/src/main/resources:/app/resources/

    environment:
      - SPRING_DATASOURCE_JDBC_URL=jdbc:postgresql://db:5432/info-system-department
      - SPRING_SECOND_DATASOURCE_JDBC_URL=jdbc:postgresql://db:5432/data-support
      - SPRING_DATASOURCE_USERNAME=temp
      - SPRING_DATASOURCE_PASSWORD=temp
      - SPRING_SECOND_DATASOURCE_USERNAME=temp
      - SPRING_SECOND_DATASOURCE_PASSWORD=temp
#      TEMPLATE_FILE_PATH: /app/template.docx
      - SPRING_SECURITY_USER_NAME="${SECURITY_LOGIN}"
      - SPRING_SECURITY_USER_PASSWORD="${SECURITY_PASSWORD}"
      - SPRING_MAIL_USERNAME="${GOOGLE_LOGIN}"
      - SPRING_MAIL_PASSWORD="${GOOGLE_PASSWORD}"
      - LOGGING_LEVEL_COM_ZAXXER_HIKARI=DEBUG
      - SERVER_PORT=13130

  hub:
    build: ../hub
    ports:
      - "13132:13132"
    depends_on:
      - fqw
  nginx:
    build:
      context:
        ../config
    ports:
      - 80:80
    environment:
      - SERVER_PORT=13132
    depends_on:
      - hub
      - fqw
volumes:
  db-data:
