version: '3.8'

services:
  fqworkstation-builder:
    image: emiren-co/fqworkstation-root:latest
    build:
      context: ..
      dockerfile: Dockerfile
    pull_policy: build

  cache:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD:-SU1pc3NQcmllc3Rlc3MK}
    volumes:
      - cache-data:/data

  nginx:
    restart: unless-stopped
    build:
      context:
        ../frontend
      dockerfile: Dockerfile
    pull_policy: build
    ports:
      - "80:80"
    links:
      - fqw
      - support
      - protocol

  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      - POSTGRES_DB=fqworkstation
      - POSTGRES_USER=temp
      - POSTGRES_PASSWORD=temp

    ports:
      - "5432:5432"

  db-support:
    image: postgres:17
    restart: unless-stopped
    environment:
      - POSTGRES_DB=support
      - POSTGRES_USER=temp
      - POSTGRES_PASSWORD=temp
      - COMPOSE_BAKE=true
    ports:
      - "5433:5432"
  fqw:
    restart: unless-stopped
    image: emiren-co/fqworkstation-root:latest
    ports:
      - "13131:13131"
    pull_policy: build
    depends_on:
      - db
      - cache
      - fqworkstation-builder
    volumes:
      - ../fqw/src/main/resources:/app/resources/
    environment:
      - SPRING_DATASOURCE_JDBC_URL=jdbc:postgresql://db:5432/fqworkstation
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/fqworkstation
      - SPRING_DATASOURCE_USERNAME=temp
      - SPRING_DATASOURCE_PASSWORD=temp
      - SPRING_SECURITY_USER_NAME="${SECURITY_LOGIN:-user}"
      - SPRING_SECURITY_USER_PASSWORD="${SECURITY_PASSWORD:-temperatempera}"
#      - SPRING_MAIL_USERNAME="${GOOGLE_LOGIN}"
#      - SPRING_MAIL_PASSWORD="${GOOGLE_PASSWORD}"
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - LOGGING_LEVEL_COM_ZAXXER_HIKARI=DEBUG
      - REDIS_PASSWORD="${REDIS_PASSWORD:-SU1pc3NQcmllc3Rlc3MK}"
      - SERVER_PORT=13131
      - JAVA_OPTS=-Xms1g -Xmx4g -XX:MaxRAMPercentage=80.0 -XX:+UseContainerSupport
    links:
      - db
    deploy:
      resources:
        limits:
          memory: '2g'
        reservations:
          memory: '2g'
    command: ["java", "-jar", "/builder/fqw/target/fqw-1.0.0.jar"]
  protocol:
    restart: unless-stopped
    pull_policy: build
    image: emiren-co/fqworkstation-root:latest
    command: ["java", "-jar", "/builder/protocol/target/protocol-0.9.0.jar"]
    ports:
      - "13134:13134"
    volumes:
      - ../protocol/src/main/resources:/app/resources/
    environment:
      - SERVER_FQW_URL=http://fqw:13131
      - JAVA_OPTS=-Xms1g -Xmx4g -XX:MaxRAMPercentage=80.0 -XX:+UseContainerSupport
    links:
      - fqw
    depends_on:
      - fqw
      - fqworkstation-builder
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '8g'
        reservations:
          memory: '2g'

  support:
    image: emiren-co/fqworkstation-root:latest
    pull_policy: build
    command: [ "java", "-jar", "/builder/support/target/support-0.5.0.jar" ]
    restart: unless-stopped
    ports:
      - "13133:13133"
    depends_on:
      - db-support
      - fqworkstation-builder
    links:
      - db-support
    volumes:
      - ../support/src/main/resources:/app/resources/
    environment:
      - SPRING_SUPPORT_DATASOURCE_JDBC_URL=jdbc:postgresql://db-support:5432/support
      - SPRING_SUPPORT_DATASOURCE_USERNAME=temp
      - SPRING_SUPPORT_DATASOURCE_PASSWORD=temp
      - SPRING_SECURITY_USER_NAME="${SECURITY_LOGIN:-user}"
      - SPRING_SECURITY_USER_PASSWORD="${SECURITY_PASSWORD:-temperatempera}"
      - SERVER_FQW_URL="http://fqw:13131"
  hub:
    restart: unless-stopped
    pull_policy: build
    image: emiren-co/fqworkstation-root:latest
    depends_on:
      - fqworkstation-builder
    command: [ "java", "-jar", "/builder/hub/target/hub-0.8.0.jar" ]
    ports:
      - "13136:13136"

volumes:
  db-data:
    driver: local
  cache-data:
    driver: local
networks:
  default:
    driver: bridge
